# Site settings
title: Blog - Patrick Sullivan
email: patrick@pdsullivan.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.pdsullivan.com" # the base hostname & protocol for your site
#url: "http:localhost:4000"
twitter_username: patsully88
github_username:  pdsullivan

# exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

# Build settings
markdown: kramdown

paginate: 5